name: Feature Request
description: New feature request
title: "Feature Title"
labels: ["kind/feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution. Before you submit the issue:
        1. Search open and closed issues for duplicates.
        2. Read the contributing guidelines.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature.
      placeholder: Type the feature description here.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reasons
      description: Explain why we should add this feature. Provide use cases to illustrate its benefits.
      placeholder: Type the feature reasoning here.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for the issue.
      value: |
       - [ ] Acceptance Criterion #1
       - [ ] Acceptance Criterion #2
    validations:
      required: true
  - type: dropdown
    id: test-suites
    attributes:
      label: Which tests should be introduced?
      multiple: true
      options:
        - Unit tests
        - Integration tests
        - E2E tests
        - Smoke test
        - Performance test
  - type: textarea
    id: testing
    attributes:
      label: Testing approach
      description: Describe the testing approach for the feature.
      placeholder: Type the testing approach in here.
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Attach any files, links, code samples, or screenshots that will convince us to your idea.
      placeholder: Put your attachments in here.
    validations:
      required: false
