name: Feature Request
description: New feature request
title: "Feature Title"
labels: ["kind/feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution. Before you submit the issue:
        1. Search open and closed issues for duplicates.
        2. Read the contributing guidelines.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature.
      placeholder: Type the feature description here.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reasons
      description: Explain why we should add this feature. Provide use cases to illustrate its benefits.
      placeholder: Type the feature reasoning here.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Tests
    attributes:
      label: Which tests should be introduced?
      multiple: true
      options:
        - Unit tests
        - Integration tests
        - E2E tests
        - Smoke test
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
