name: PR title checker

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: ".commitlint.js"
          # If the PR contains a single commit, fail if the commit message and the PR title do not match.
          commitTitleMatch: "false"
          # Disable linting of any commits due to the "Squash Merging" PR workflow.
          ignoreCommits: "yes"
