name: Report Package Metrics
run-name: Generate package dependencies report

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  spm: ${{ github.workspace }}/.scripts/scripts/spm.py
  compare: ${{ github.workspace }}/.scripts/scripts/compare.py
  pip_requirements: ${{ github.workspace }}/.scripts/scripts/requirements.txt
  base: /tmp/base.json
  target: /tmp/target.json

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: target/
      - name: Check out the base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base/
      - name: Check out report scripts
        uses: actions/checkout@v4
        with:
          repository: ameteiko/impetus_core
          path: scripts/
          sparse-checkout: |
            coverage-metrics/bin/utils/package-metrics
      - name: Prepare the highlighter utility
        run: |
          ls ${{ github.workspace }}/scripts
          ls ${{ github.workspace }}/base
          ls ${{ github.workspace }}/target
          chmod a+x $spm
          chmod a+x $compare
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $pip_requirements
      - name: Genarate a report
        run: |
          $spm --path ${{ github.workspace }} --module github.com/ameteiko/goreleaser --out $target
          $spm --path ${{ github.workspace }}/.base --module github.com/ameteiko/goreleaser --out $base
          $compare --base $base --target $target
