name: Report Package Metrics
run-name: Generate package dependencies report

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  glossaryURL: https://github.com/kyma-project/lifecycle-manager/wiki/Glossary.md
  # The report highlighter utility that is checked out from the
  # https://github.com/kyma-project/qa-toolkit/blob/main/coverage-metrics/bin/utils/report-highlighter/highlighter.py
  scripts_path: ${{ github.workspace }}/.scripts/scripts
  spm: $scripts_path/spm.py
  compare: $scripts_path/compare.py
  base: /tmp/base.json

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out LM source code
        uses: actions/checkout@v4
      - name: Check out report scripts
        uses: actions/checkout@v4
        with:
          repository: ameteiko/impetus_core
          path: .scripts
          sparse-checkout: |
            scripts
      - name: Prepare the highlighter utility
        run: |
          chmod a+x $spm
          chmod a+x $compare
      - name: Install dependencies
        run: |
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
      - name: Genarate a report
        run: |
          $spm --path ${{ github.workspace }} --module github.com/ameteiko/goreleaser --out $base
          cat $base
