name: Quality Gate for the Unit Test Coverage

on: workflow_dispatch

env:
  coverage_guard: ${{ github.workspace }}/scripts/coverage-metrics/bin/utils/unit-test-coverage/coverage_guard.py
  pip_requirements: ${{ github.workspace }}/scripts/coverage-metrics/bin/utils/unit-test-coverage/requirements.txt

jobs:
  assess-unit-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out report scripts
        uses: actions/checkout@v4
        with:
          repository: ameteiko/impetus-core
          path: scripts
      - name: Check out the sourcecode
        uses: actions/checkout@v4
        with:
          repository: kyma-project/lifecycle-manager
          path: base
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1' 
      - name: Adjust the metrics utilities
        run: |
          chmod a+x $coverage_guard
          python -m pip install --upgrade pip
          pip install -r $pip_requirements
      - name: create a config
        run: |
          echo -e "packages:\n  pkg/security: 10" > ${{ github.workspace }}/base/config.yaml
      - name: Genarate a report
        run: |
          $coverage_guard --repo ${{ github.workspace }}/base --module github.com/kyma-project/lifecycle-manager --config config.yaml 
